name: CI - Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  notify-on-failure:
    needs: test
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send email on failure
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: 'CI failed — calculadora-simples'
          to: ${{ secrets.ALERT_EMAIL_TO }}
          from: ${{ secrets.ALERT_EMAIL_FROM }}
          body: 'A pipeline de testes falhou. Verifique o run do GitHub Actions.'
